### ISSUE TITLE
2 pixels giving problems

### ISSUE THREAD

**Issue by shamoonak** [oleg-dirtrider/gtm_template_ga_ecommerce_data_transfer_to_remarketing_pixels#2]
I have a client with an ecommerce store built in opencart. They are running their own facebook pixel with the official facebook extension for opencart. I need another pixel installed so I used google tag manager. I am using the Google Tag Manager template for Facebook pixel by Simo Ahava to fire the pixel across the website. I need to use that because if I only use your template, the pixel is not firing on other events.

The problem I'm having is that your template isn't passing the ecommerce variables to the facebook pixel all the time. 1 out of 20 times, it will fire another event and pass the variables to those. So I get 2 Purchase events fired, one has no variables forwarded to it, the second one has all the variables required forwarded.

I need it to fire all the time, and for there to be one of each events required. How do I get that done?

Thank you in advance!!!!

**Comment by d9i2r2t1** [comment]
Hello!
My template doesn't add ecommerce data in existing event, it sends it's own event.

You have 2 Purchase events fired because first event it's your pixel's event (from Simo Ahava's Facebook pixel template and it has no variables forwarded to it) and second event it's my template event which has ecommerce data.

You should to fire your own FB pixel tag only on those events that are NOT tracked by mine template.
You can see events that are tracked by my template for FB pixel here: https://github.com/oleg-dirtrider/gtm_template_ga_ecommerce_data_transfer_to_remarketing_pixels#fb_pixel

For example: you can track Pageview event, AddToWishlist event, FindLocation event by your FB pixel GTM tag, but AddToCart, Purchase, Checkout you should track only by my template, because it will send events to FB itself, it will not modify events that are pushed by your own FB pixel tag.

Please tell me if this helped you.

**Comment by shamoonak** [comment]
Thanks! It solved my problem with the Purchase event. Now it's getting all the data. The InitiateCheckout event is not firing though. It does solve my problem since I needed to get the AddToCart and Purchase events working.

If there's something I'm missing for InitiateCheckout, or something I need to check do let me know. Otherwise, things are good for me.

Grateful for your help!

**Comment by d9i2r2t1** [comment]
I guess that you don't have actionField object in your dataLayer.push ecommerce checkout event, because it's not necessary for checkout event.

I just updated the template, now it should track checkout events without actionField object.
Please check it, I hope it will work for you.

In actionField object you can set different event parameters, for example current step of checkout chain:

_dataLayer.push({
    'event': 'checkout',
    'ecommerce': {
        'checkout': {
            'actionField': {**'step': 1**, 'option': 'value'},
            'products': [{...}]
    }
})_

Usually there are several steps in checkout chain. For example: step 1 is when order page is loaded, step 2 is when user set his contacts and etc. But this parameters are not required for checkout events.

Previously, my template tracked checkout events only if the parameter '_step_' was set and if it was =1. I’ll say from my experience that usually first checkout step is enough to set up remarketing.

Now after fix it should work if actionField object is not specified or if there is no '_step_' parameter in actionField object. 
If you will set '_step_' parameter my template will work as previously: it will track checkout event only of it's first step of checkout chain.

**Comment by shamoonak** [comment]
Thank you for your help!
